<a href="https://colab.research.google.com/github/Tharunakula/Home-Assignment-2/blob/main/Q2.Convolution%20Operations%20with%20Different%20Parameters.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

2.Convolution Operations with Different Parameters

In [1]:
import numpy as np
import tensorflow as tf

def perform_convolution(input_matrix, kernel, strides, padding):
    """
    Performs convolution on an input matrix with specified kernel, strides, and padding.

    Args:
        input_matrix: A NumPy array representing the input matrix.
        kernel: A NumPy array representing the kernel.
        strides: An integer representing the stride.
        padding: A string representing the padding ('VALID' or 'SAME').

    Returns:
        A NumPy array representing the output feature map.
    """

    # Add batch and channel dimensions
    input_tensor = tf.constant(input_matrix.reshape((1, 5, 5, 1)), dtype=tf.float32)
    kernel_tensor = tf.constant(kernel.reshape((3, 3, 1, 1)), dtype=tf.float32)

    # Perform convolution
    output_tensor = tf.nn.conv2d(
        input_tensor,
        kernel_tensor,
        strides=[1, strides, strides, 1],
        padding=padding
    )

    # Remove batch and channel dimensions and return as NumPy array
    return output_tensor.numpy().reshape(output_tensor.shape[1], output_tensor.shape[2])

# Define input matrix and kernel
input_matrix = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25]
])

kernel = np.array([
    [0, 1, 0],
    [1, -4, 1],
    [0, 1, 0]
])

# Perform convolution with different parameters
results = {}

results['Stride=1, Padding=VALID'] = perform_convolution(input_matrix, kernel, strides=1, padding='VALID')
results['Stride=1, Padding=SAME'] = perform_convolution(input_matrix, kernel, strides=1, padding='SAME')
results['Stride=2, Padding=VALID'] = perform_convolution(input_matrix, kernel, strides=2, padding='VALID')
results['Stride=2, Padding=SAME'] = perform_convolution(input_matrix, kernel, strides=2, padding='SAME')

# Print the output feature maps
for key, value in results.items():
    print(f"{key}:\n{value}\n")

Stride=1, Padding=VALID:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Stride=1, Padding=SAME:
[[  4.   3.   2.   1.  -6.]
 [ -5.   0.   0.   0. -11.]
 [-10.   0.   0.   0. -16.]
 [-15.   0.   0.   0. -21.]
 [-46. -27. -28. -29. -56.]]

Stride=2, Padding=VALID:
[[0. 0.]
 [0. 0.]]

Stride=2, Padding=SAME:
[[  4.   2.  -6.]
 [-10.   0. -16.]
 [-46. -28. -56.]]

